plugins {
    id 'org.moddingx.modgradle.meta' version '5.1.5'
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

var dev = System.getenv('IS_DEV')?.toBoolean() ?: false
var releaseType = 'beta'
var baseVersion = '26.2'
var cherishedWorldsVersion = 'bK316SkZ' // 13.0.1+1.21.8

mod.configure {
    modid 'simplebackups'
    group 'de.melanx'
    versioning {
        if (dev) {
            def gitCommitHash = ['git', 'rev-parse', 'HEAD'].execute().text.trim()
            constant baseVersion + '.999' + (gitCommitHash ? "-${gitCommitHash}" : '')
        } else {
            base baseVersion
            maven 'https://maven.melanx.de/release'
        }
    }

    neoforge "${baseVersion}.0.7-beta"

    license 'The Apache License, Version 2.0'
    github 'ChaoticTrials/SimpleBackups'

    artifacts {
        sources {
            publishToRepositories()
        }
        extra('jarJar') {
            classifier 'zstd'
            publishToRepositories()
            uploadToModHostingSites()
        }
    }

    changelog {
        def lines = defaultChangelog.toString().split('\n')
        def filteredChangelog = lines.findAll { !it.startsWith('- [[meta]') }.join('\n')

        return filteredChangelog
    }


    publishing {
        maven {
            name 'melanx'
            url 'https://maven.melanx.de/release'
            credentials(PasswordCredentials)
        }
    }

    upload {
        all {
            type releaseType
            environmentType 'client_and_server_optional'
            version '26.2'
            optional 'cherished-worlds'
        }
        curseforge {
            projectId 583228
        }
        modrinth {
            projectId 'fzSKSXVK'
        }
    }
}

tasks.named('jarJar') {
    from('licenses/zstd-jni.txt') {
        into('META-INF/LICENSES')
    }

    from('licenses/xz.txt') {
        into('META-INF/LICENSES')
    }
}

dependencies {
    compileOnly "maven.modrinth:cherished-worlds:${cherishedWorldsVersion}"

    implementation(jarJar('org.tukaani:xz:1.12'))
    implementation(jarJar('com.github.luben:zstd-jni:1.5.7-7'))
}
