modLoader="javafml"
loaderVersion="[42,)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/SkyblockBuilder/issues"

[[mods]]
modId="simplebackups"
version="${version}"
displayName="Simple Backups"
updateJSONURL="https://assets.melanx.de/updates/simple-backups.json"
displayURL="https://www.curseforge.com/members/melanx/"
authors="MelanX"
displayTest="IGNORE_ALL_VERSION"
description="""
A simple mod to create scheduled backups.
"""

[[dependencies.simplebackups]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplebackups]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1, 1.20)"
    ordering="NONE"
    side="BOTH"
