modLoader="javafml"
loaderVersion="[${fml},)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/SkyblockBuilder/issues"

[[mods]]
modId="simplebackups"
version="${version}"
displayName="Simple Backups"
updateJSONURL="https://assets.melanx.de/updates/simple-backups.json"
displayURL="https://www.curseforge.com/members/melanx/"
authors="MelanX"
description="""
A simple mod to create scheduled backups.
"""

[[dependencies.simplebackups]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplebackups]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft},)"
    ordering="NONE"
    side="BOTH"
