modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL = "https://github.com/ChaoticTrials/SimpleBackups/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Simple Backups"
updateJSONURL = "https://assets.melanx.de/updates/simple-backups.json"
displayURL = "https://modrinth.com/user/MelanX"
authors = "MelanX"
displayTest = "IGNORE_ALL_VERSION"
description = '''
A simple mod to create scheduled backups.
'''

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
