modLoader="javafml"
loaderVersion = "[4,)"
license = "${mod.license}"
issueTrackerURL = "${mod.issue_url}"

[[mods]]
modId = "${mod.modid}"
version = "${mod.version}"
displayName = "Simple Backups"
displayURL = "${mod.source_url}"
updateJSONURL = "https://assets.melanx.de/updates/simple-backups.json"
authors = "MelanX"
displayTest = "IGNORE_ALL_VERSION"
bannerFile="${mod.modid}_logo.png"
iconFile="${mod.modid}_icon.png"
description = '''
A simple mod to create scheduled backups.
'''

[[dependencies.${ mod.modid }]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${mod.neoforge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${ mod.modid }]]
    modId="minecraft"
    type="required"
    versionRange = "[${mod.minecraft},)"
    ordering="NONE"
    side="BOTH"
