modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${license}"
issueTrackerURL = "https://github.com/ChaoticTrials/SimpleBackups/issues"

[[mods]]
modId = "${modid}"
version = "${mod_version}"
displayName = "Simple Backups"
updateJSONURL = "https://assets.melanx.de/updates/simple-backups.json"
displayURL = "https://modrinth.com/user/MelanX"
authors = "MelanX"
displayTest = "IGNORE_ALL_VERSION"
description = '''
A simple mod to create scheduled backups.
'''

[[dependencies.${ modid }]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"
