name: 'Build test version'
on:
  push:
    branches:
      - 'issue/*'
      - 'pr/*'
      - 'fix/*'
      - 'feature/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        run: |
          chmod +x gradlew 
          ./gradlew build

      - name: Get current branch name
        id: get_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" | tr / - >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.branch_name }}
          path: |
            build/libs/*.jar
